language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "15"
git:
  depth: 3
script:
  - npm run build
#  - echo 'cv.arepa.dev' > public/CNAME
deploy:
  name: Elmo@gremlim
  provider: pages
  strategy: git
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: master
  commit_message: "Elmo@gremlim - Deploy release ${TRAVIS_TAG}"
  #fqdn: cv.arepa.dev
  on:
    branch: develop
after_deploy:
  cleanup: true
